using System.Globalization;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using System.Xml.Linq;
using static System.Runtime.InteropServices.JavaScript.JSType;
Console.WriteLine("Hello world100");
Console.WriteLine("Hello world200");
Console.WriteLine("Hello world300");
Console.WriteLine("Hello world400");
Console.WriteLine("Hello world500");
Console.WriteLine("Hello world600");
Console.WriteLine("Hello world700");
Console.WriteLine("Hello world800");
Console.WriteLine("Hello world900");
Console.WriteLine("Hello world1000");
