using System.Globalization;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Text;
using System.Xml.Linq;
using static System.Runtime.InteropServices.JavaScript.JSType;
Console.WriteLine("Hello world10");
Console.WriteLine("Hello world20");
Console.WriteLine("Hello world30");
Console.WriteLine("Hello world40");
Console.WriteLine("Hello world50");
Console.WriteLine("Hello world60");
Console.WriteLine("Hello world70");
Console.WriteLine("Hello world80");
Console.WriteLine("Hello world90");
Console.WriteLine("Hello world100");
